#!/usr/bin/env python

import sys
import os
import platform
from urllib import quote

link = sys.argv[1]

LinuxFavoriteTerminal = "/usr/bin/gnome-terminal"

def extractHostname(url):
  hostname = ""
  if url.index("//") > -1:
    hostname = url.split('/')[2]
  else:
      hostname = url.split('/')[0]
  hostname = hostname.split(':')[0]
  hostname = hostname.split('?')[0]
  return hostname

command="ssh $USER@" + extractHostname(link)
if platform.system() == "Linux":
  # os.system("export DISPLAY=:0 ; /usr/local/bin/terminator -e \"/bin/bash -c '" + command + "'\" &")
  os.system("export DISPLAY=:0 ; " + LinuxFavoriteTerminal + " -e \"/bin/bash -c '" + command + "'\" &")
elif platform.system() == "Darwin":
  os.system("export DISPLAY=:0 ; open -n -a Terminal \"/bin/bash -c '" + command + "'\" &")
else:
  print "Unknown platform : ", platform.system()
